// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhuicppwcdnpzkngdeeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJodWljcHB3Y2RucHprbmdkZWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjQ1OTksImV4cCI6MjA2ODI0MDU5OX0.Z6ofpgLkgKl-V_Zjce-CVKIlv7i6D1yIJaonyDl6ZM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});